# Generated by Django 3.0.3 on 2020-04-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('pno', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=30)),
                ('pprice', models.FloatField()),
                ('pquatity', models.IntegerField()),
                ('pimage', models.ImageField(upload_to='product/')),
            ],
        ),
    ]
